/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.express.bank;

import com.google.common.base.Predicates;
import com.google.common.collect.Collections2;
import com.google.common.collect.Lists;
import java.util.Collection;
import java.util.List;

public class App {

    public static void main(String[] args) {
        List<String> items = Lists.newArrayList("football", "golf",
                "basketball", "handball", "baseball", "swimming", "biathlon", "cricket");
        Collection<String> result  = Collections2.filter(items,
                Predicates.containsPattern("ball"));

        for (String item: result) {
            System.out.println(item);
        }

    }
}
